[project]
name = "style-tests"
version = "0.1.0"
description = "TestCase checking the code quality"
authors = [{ name = "Filip Zyzniewski", email = "filip.zyzniewski@gmail.com" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = "Apache License 2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pylint>=3.0.3,<4",
    "black>=24.1.1,<25",
    "isort>=5.13.2,<6",
    "pycodestyle>=2.11.1,<3",
]

[dependency-groups]
test = ["typeguard>=4.1.5,<5"]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
